### ISSUE TITLE
Calibration information

### ISSUE THREAD

**Issue by lywcn** [rising-turtle/VCU_RVI_Benchmark#1]
Thank you very much for providing this useful dataset!!!

I am wondering if you can also provide your calibration results (camera, camera-imu etc). Thank you!

**Comment by rising-turtle** [comment]
Hi @lywcn : 

Thanks for your interest. The camera's data (color and depth) were collected with two preprocessing steps: 1. the structure core was configed in the undistortion mode, which means the color images were undistorted by the structure core driver; 2. the raw depth images were used to generate virtual depth images, which are pixel-wise corresponding to the color images, via the transformation between the left IR camera and the color camera. Therefore, for the color camera, its distortion free intrinsic parameters were obtained from the driver:    
fx: 459.357, fy: 459.764, cx: 332.695, cy: 258.998,  k1: 0. , k2: 0., p1: 0., p2: 0. 
The camera-imu transformation matrix is: 
R = [0.00193013, -0.999997, 0.00115338, 
            -0.999996, -0.0019327, -0.00223606, 
            0.00223829, -0.00114906, -0.999997]
t = [-0.00817048, 0.015075, -0.0110795]
There are some examples to set up these parameters in VIO, which might be also helpful. 
https://github.com/rising-turtle/VINS-Mono/blob/master/config/struct_core_config.yaml
https://github.com/rising-turtle/VINS-RGBD/blob/master/config/struct_core/struct_core_color_config.yaml

Hopefully, it will be helpful.

**Comment by lywcn** [comment]
cool! The yaml file is exactly what I need for now.

**Comment by chenguilin111** [comment]
> Hi @lywcn :
> 
> Thanks for your interest. The camera's data (color and depth) were collected with two preprocessing steps: 1. the structure core was configed in the undistortion mode, which means the color images were undistorted by the structure core driver; 2. the raw depth images were used to generate virtual depth images, which are pixel-wise corresponding to the color images, via the transformation between the left IR camera and the color camera. Therefore, for the color camera, its distortion free intrinsic parameters were obtained from the driver: fx: 459.357, fy: 459.764, cx: 332.695, cy: 258.998, k1: 0. , k2: 0., p1: 0., p2: 0. The camera-imu transformation matrix is: R = [0.00193013, -0.999997, 0.00115338, -0.999996, -0.0019327, -0.00223606, 0.00223829, -0.00114906, -0.999997] t = [-0.00817048, 0.015075, -0.0110795] There are some examples to set up these parameters in VIO, which might be also helpful. https://github.com/rising-turtle/VINS-Mono/blob/master/config/struct_core_config.yaml https://github.com/rising-turtle/VINS-RGBD/blob/master/config/struct_core/struct_core_color_config.yaml
> 
> Hopefully, it will be helpful.

Thank you very much for your answers to the previous questions.
I have a question here, noise and random walking at vins-mono/blob/master/config/struct_core_config.yaml) are
acc_n: 0.1
gyr_n: 0.01
ACC_W: 0.001
gyr_w: 0.0001
But in VINS-RGBD/Blob/Master/Config/Struct_core/Struct_Core_CONFIG.YAML IS
acc_n: 0.3
gyr_n: 0.02
ACC_W: 0.001
gyr_w: 0.0001
Is it better to set up the values ​​in our actual use of data sets? It doesn't seem to be seen in the data set.
