### ISSUE TITLE
The size of the valid depth value 

### ISSUE THREAD

**Issue by jzhzhang** [rising-turtle/VCU_RVI_Benchmark#10]
Hi, thanks for your benchmark.

I find that the size of the valid depth value is cropped. Are there any additional operations on the depth maps? Or is it something to do with the depth-to-RGB calibration?
![Snipaste_2022-06-07_13-20-18](https://user-images.githubusercontent.com/54199992/172301813-7601c5d5-ed96-4f5d-b500-ae85ae6983e4.png)

**Comment by rising-turtle** [comment]
The raw depth image and the color image have different resolutions. The depth images that you saw from the bag files had been aligned with the color image, resulting in a 1-to-1 correspondence for each pixel.  So, the answer is yes, the raw depth data is mapped to 3D space and then reprojected onto the color image to create the aligned depth images.

**Comment by jzhzhang** [comment]
Thanks for your clarification.
