### ISSUE TITLE
Open source DUI-VIO?

### ISSUE THREAD

**Issue by lywcn** [rising-turtle/VCU_RVI_Benchmark#2]
Thank you for your great work! I was wondering if you are going to open source your DUI-VIO SLAM?

**Comment by rising-turtle** [comment]
@lywcn 
Yes, I was working on that. Need to first extract the code from our project and make it clean and tight.

**Comment by lywcn** [comment]
Cool! Thank you!

**Comment by lywcn** [comment]
I am wondering if the DUI-VIO SLAM is available now? Thank you!

**Comment by rising-turtle** [comment]
> I am wondering if the DUI-VIO SLAM is available now? Thank you!

Sorry for the late reply, and I have been glued to job hunting. Now the DUI-VIO is open sourced, please check on it at https://github.com/rising-turtle/DUI_VIO. Thanks.

**Comment by lywcn** [comment]
Great! Thank you!
