### ISSUE TITLE
Possible wrong GT for handheld hall 03

### ISSUE THREAD

**Issue by lywcn** [rising-turtle/VCU_RVI_Benchmark#3]
Hi, there

For your VCU-RVI dataset at https://vcu-rvi-dataset.github.io/, it seem the handheld-hall-03 set has a wrong GT trajectory file. Basically the file name is not the same and the timing within it is also not aligned with the bag file. Can you please take a look at it? Thank you!

The bag file has imu infos:
timestamp,omega_x,omega_y,omega_z,alpha_x,alpha_y,alpha_z
3742332475130,-0.0021279999054968357,-0.0085119996219873428,-0.0021279999054968357,9.79888,0.252859,-0.349877
3742342488624,-0.0015959999291226268,-0.013831999152898788,-0.0031919998582452536,9.82318,0.180522,-0.194801
3742352498981,-0.0031919998582452536,-0.028195999562740326,-0.0074479999020695686,9.82669,0.205572,-0.248657
3742362513589,0.0015959999291226268,-0.038835998624563217,-0.01170399971306324,9.81798,0.197934,-0.308549
3742372532045,-0.0053199995309114456,-0.03564399853348732,-0.011171999387443066,9.75208,0.277697,-0.487423
3742382545992,-0.0026599997654557228,-0.018087999895215034,-0.00585199985653162,9.70918,0.295532,-0.599139
3742392561339,0.0015959999291226268,0.0037239999510347843,0.0010639999527484179,9.73423,0.231769,-0.496669
3742402569600,-0.0069159995764493942,0.018619999289512634,0.0063839997164905071,9.7593,0.195042,-0.409804
3742412588785,0.0026599997654557228,0.017555998638272285,0.0085119996219873428,9.78972,0.145147,-0.346825

The GT has infos:
226.740069808 0.000000 -0.000000 0.000000 -0.000000 -0.000000 0.000000 1.000000
226.748403808 0.000000 0.000006 -0.000010 0.000015 -0.000002 0.000019 1.000000
226.756736808 0.000007 0.000001 -0.000013 0.000026 -0.000021 0.000049 1.000000
226.765069808 0.000017 -0.000008 -0.000016 -0.000001 -0.000084 0.000045 1.000000
226.773403808 0.000007 -0.000013 -0.000012 -0.000011 -0.000026 -0.000014 1.000000
226.781736808 0.000003 -0.000016 -0.000014 0.000044 -0.000001 -0.000006 1.000000
226.790069808 -0.000001 -0.000019 -0.000012 0.000039 0.000018 0.000012 1.000000
226.798403808 -0.000002 -0.000019 -0.000012 0.000050 -0.000020 -0.000015 1.000000
226.806736808 0.000002 -0.000022 -0.000014 0.000009 -0.000026 -0.000009 1.000000
226.815069808 -0.000003 -0.000015 -0.000018 0.000047 0.000051 0.000000 1.000000

**Comment by rising-turtle** [comment]
Hi @lywcn:
Thank you for reporting that. The GT file for Hall 3 has been updated. Please download the updated file to check out. 
Sorry for the inconvenience, and I will re-examine the content of the download website next week. 

Best,

**Comment by lywcn** [comment]
I just checked https://drive.google.com/file/d/1Jp8L1FDsBOVpBpdwF-r753eP1T7md-Lj/view?usp=sharing 
it seems the file is the same?

**Comment by rising-turtle** [comment]
Hi @lywcn : 
The bag file is also updated, and please redownload it as well. 

best,

**Comment by lywcn** [comment]
Great! The data set is fine now. thank you!

By the way, I am wondering if you can provide the settings for the VINS-Mono and VINS-RGBD settings to run the data set. I run the those two SLAMs on your data set and it seems the results are not matched with the results provided in your paper http://ras.papercept.net/images/temp/IROS/files/0685.pdf , e.g. table 3.

I also cloned your modified VINS-Mono repo https://github.com/rising-turtle/VINS-Mono. Run it with struct_core.launch. But the results are not saved in csv. It may not be the right repo?

**Comment by rising-turtle** [comment]
@lywcn : 
For VINS-Mono and VINS-RGBD, please use the modified version in https://github.com/rising-turtle/VINS-Mono and https://github.com/rising-turtle/VINS-RGBD , respectively. 

I just run the VINS-Mono on my computer, and it can generate csv trajectory file (vins_result_no_loop.csv or vins_result_loop.csv if loop closure is enabled) with no problem. Notice, the variable "output_path" (in struct_core_config.yaml) needs to be changed according to your pc folder setup.

To reproduce the results in table 3, you need to follow the method described in section V.A in the paper, which I am working on to add in the download page. I will let you know once that part (including the script files) is uploaded. Currently, however, the results can be evaluted by using some other standard tools, like evo https://github.com/MichaelGrupp/evo. 

best,

**Comment by rising-turtle** [comment]
@lywcn :
For VINS-Mono and VINS-RGBD, please use the modified version in https://github.com/rising-turtle/VINS-Mono and https://github.com/rising-turtle/VINS-RGBD , respectively.

I just run the VINS-Mono on my computer, and it can generate csv trajectory file (vins_result_no_loop.csv or vins_result_loop.csv if loop closure is enabled) with no problem. Notice, the variable "output_path" (in struct_core_config.yaml) needs to be changed according to your pc folder setup. 

To reproduce the results in table 3, you need to follow the method described in section VI.A in the paper, which I am working on to add in the download page. I will let you know once that part (including the script files) is uploaded. Currently, however, the results can be evaluted by using some other standard tools, like evo https://github.com/MichaelGrupp/evo.

best,

**Comment by lywcn** [comment]
Thank you for your reply! Yes. I am using EVO and the results are different. One main reason I see is that EVO uses Umeyama matching (without scaling) to find T for the whole sequences. But in your paper, it seems you are matching the very beginning of the sequences. 

No problem. Thank you and I am looking forward to your evaluation scripts!

**Comment by rising-turtle** [comment]
Yes, you are right. Will release the evaluation session in the download page soon. 

Thanks.
