### ISSUE TITLE
OpenVINS evaluation accuracy.

### ISSUE THREAD

**Issue by Boyuan-Tian** [rising-turtle/VCU_RVI_Benchmark#6]
Hi,

I am testing the lab-simple1 sequence with the OpenVINS provided in the [VCU-RVI benchmark](https://github.com/rising-turtle/open_vins).

However, I had some difficulties reproducing the result shown in the following figure. Could you please give me any hints?

![unnamed](https://user-images.githubusercontent.com/18485088/127468182-bf33bedb-eda7-4e9d-b5b0-14e053e923df.png)

## Following are the steps I did to get the result.
- Run the OpenVINS above with lab-simple1.bag. 
- Run `process_result.py` to get the `TUM` file and apply time offset.
    - This is the original estimated trajectory collected by OpenVINS ([estimate_tum.csv](https://github.com/rising-turtle/VCU_RVI_Benchmark/files/6899414/estimate_tum.csv)), and this is the processed trajectory ([zero_estimate_tum.csv](https://github.com/rising-turtle/VCU_RVI_Benchmark/files/6899423/zero_estimate_tum.csv)).
- Run `evo_ape tum lab_simple1_gt.csv zero_estimate_tum.csv -p` to analyze the error.
    - This is the groundtruth I used [lab_simple1_gt.csv](https://github.com/rising-turtle/VCU_RVI_Benchmark/files/6899453/lab_simple1_gt.csv), and this is the ATE figure I got both with and without alignment.
![lab-simple1-align](https://user-images.githubusercontent.com/18485088/127467774-1c9500e2-7797-40e8-b366-417e25e400ca.png)
![lab-simple1-no-align](https://user-images.githubusercontent.com/18485088/127467790-c4ee1eb1-9e87-4a27-9548-0d45d11e6fcc.png)

The mean ATE error is around 0.4 and 1.4, respectively, while the figure at the beginning is around 0.1.

The only place I changed in the original code is [here](https://github.com/rising-turtle/VCU_RVI_Benchmark/blob/master/tools/process_result.py#L68), where I commented out the `/1e9` since it results in the inconsistent data format of timestamp with groundtruth.

Thanks for your help!

**Comment by rising-turtle** [comment]
Hi @Boyuan-Tian  thank you for testing. OpenVINS uses a simple initialization strategy (average several measurements of the accelarometer and the gyroscope as the inital biases by assuming the device is static in the first several seconds) to compute the VINS' initial state. It causes the large pose errors as the data sequences were not recorded fully static in the beginning. The authors of OpenVINS would integrate the optimization based initialization approach in the future, which you can check their TODO list. For now, I recommend to try the other three methods (VINS-Mono, VINS-RGBD, DUI-VIO) to test the benchmark. Thanks.

**Comment by Boyuan-Tian** [comment]
Hi @rising-turtle I see. Thanks for your explanation. I'll try the other methods as well.
