### ISSUE TITLE
The results in "test_results"

### ISSUE THREAD

**Issue by jzhzhang** [rising-turtle/VCU_RVI_Benchmark#7]
Thanks for your great dataset.

I encountered some problems while using the given results:

1. I found that the results are slightly different from the paper.  e.g:
``` evo_ape tum tools/test_results/dui-vio/lab_motion6_tum.csv  tools/ground_truths/lab_motion6_gt.csv``` 

the rmse of the above command is 0.645723, and the paper gives 0.592

2. Some results are missing, I can not find the lab-bumper5_tum trajectory of DUI-VIO or VINS-RGBD. And what is the meaning of ```using all pose to compute transformation matrix T for alignment``` in the paper? 

3. Are the sequences number related to the speed or something else?

The dataset really helps the community to investigate the benefit of IMU with RGBD. Really appreciate your efforts and hope you can clarify the mentioned problems.

**Comment by rising-turtle** [comment]
Hi @jzhzhang, thanks for your interest. I cannot remember exactly how to get the best rmse with lab_motion6 dataset, you might try fine-tune the parameters (e.g. bias and noise std). 

Run DUI-VIO and VINS-RGBD with lab-bumper5 lead the vins-estimator fail to converge leading to very large error. This case is considered a failure and the result is not kept. 

"using all pose to compute transformation matrix T for alignment" means first, compute a transformation matrix T between the estimated trajectory and the ground truth trajectory; second, transforms the estimated trajectory using T, attempting to align with the ground truth, and then compute the rmse between the transformed trajectory and the ground truth. On the contrary to this, is "using a small portion of the trajectory to compute the transformation matrix T", like the first 100 poses, and then do the alignment and error computation. 

The sequence number does not have a particular meaning regards to the property of the dataset, and it is only an index.

**Comment by jzhzhang** [comment]
Thanks for your explanation.  I will close this issue.
