### ISSUE TITLE
the acce data formet of VCU-RVI dataset 

### ISSUE THREAD

**Issue by weiningwei** [rising-turtle/VCU_RVI_Benchmark#8]
Hello, thank you for the work. But when I use this dataset to test other VIO method, unlike other datasets, the acceleration data are normalized, meaning that when the IMU is stationary, the acceleration data should be 9.8, but the data of rosbag is -1.
Can you tell me some detailed steps for testing othering VIO methods, such as those changes you made when debugging VINS-Mono?

**Comment by rising-turtle** [comment]
The acc data captured by structure core is normalized, for example, if ax is 7.1, it will be converted to 7.1/9.8 = 0.724. So, to use this data in DUI-VIO, what I do is something like below: 
'''
   double nG = -9.8; 
   double dx = imu_msg->linear_acceleration.x*nG;
   double dy = imu_msg->linear_acceleration.y*nG;
   double dz = imu_msg->linear_acceleration.z*nG;
   Eigen::Vector3d linear_acceleration{dx, dy, dz};
'''
You might need to multiply the acc data by -9.8, depending on the IMU coordinate system defined by the VIO method you test.

**Comment by rising-turtle** [comment]
The acc data captured by structure core is normalized, for example, if ax is 7.1, it will be converted to 7.1/9.8 = 0.724. So, to use this data in DUI-VIO, what I do is something like below:
```c++  
double nG = -9.8;   
double dx = imu_msg->linear_acceleration.x * nG;    
double dy = imu_msg->linear_acceleration.y * nG;   
double dz = imu_msg->linear_acceleration.z * nG;   
Eigen::Vector3d linear_acceleration{dx, dy, dz};   
```   
You might need to multiply the acc data by -9.8, depending on the IMU coordinate system defined by the VIO method you test.

**Comment by weiningwei** [comment]
OK, thank you for the immediate reply . I will try it soon.
